#!/usr/bin/env python3
"""gen.py — single, SAFE entrypoint for GAM code generation.

Consolidates the 4 bootstrap generators behind one subcommand interface and
makes generation non-destructive: **dry-run by default** (prints a diff),
``--write`` to apply, and every target is gated because — as a dry-run proves
— the generators have **drifted behind the hand-maintained live backend** and
are now STALE. The live files under ``~/frappe-bench/apps/gam`` are the source
of truth.

⚠️  READ THIS BEFORE ``--write``:
  A dry-run (see ``python gen.py all``) shows that regenerating ANY target
  would clobber live improvements that post-date the generators — e.g. the L2
  access-grants boot block in ``utils.py``, the ``emit_account_changed`` /
  ``emit_role_sections_changed`` realtime helpers, and the ``grant_default_policy``
  field on ``gam_settings.json``. The generators were bootstrap scaffolding;
  the live backend has since grown beyond them.

  => Do NOT run ``--write`` to "fix" drift. To make a generator authoritative
     again you must FIRST regenerate its template FROM the live file (plans P4.4),
     then ``gen.py <target> --write`` will be a true no-op.

Targets (see ``python gen.py status``):
  backend   STALE           .gen_backend.py    utils/realtime/tasks/setup/permission/ops.py + hooks patch
  doctypes  STALE           .gen_doctypes.py   16 doctypes (field order + grant_default_policy drift)
  tests     STALE           .gen_tests.py      live tests/ has grown (test_security.py for P1.3/P1.5/P1.6)
  api       STALE/DESTRUCT  .gen_api.py        live api.py (~1800 lines) is the source of truth

Usage:
  python gen.py status                 # print target health (all STALE today)
  python gen.py backend                # dry-run: diff generator output vs live (read-only)
  python gen.py all                    # dry-run every non-destructive target (drift report)
  python gen.py backend --write        # REFUSED (stale) unless --force
  python gen.py backend --write --force   # apply anyway (you regenerated the template first)

Safety model:
  * Default mode is DRY-RUN — no file is written. Each generator's ``open(...)``
    calls are captured via a temporary monkeypatch and diffed against the live
    file, so drift is visible before it is applied.
  * ``--write`` on a STALE target is refused without ``--force`` (and prints the
    warning above), so a careless ``gen.py all --write`` can never silently
    clobber the live backend.
  * ``--banner`` (opt-in, off by default) prepends a ``# DO NOT EDIT — generated
    by gen.py`` header to ``.py`` outputs. It is OFF by default because the live
    files are hand-maintained, NOT generated — bannering them would be a lie.
    Enable it only for a target you have regenerated to be authoritative.
  * If ``~/frappe-bench/apps/gam`` is absent (e.g. hosted CI), dry-run exits 0
    with "backend not present" — so this command is safe to run in CI today and
    becomes a real idempotent guard automatically once the backend lands in-repo
    (plans P4.3) AND the generators are regenerated to match (plans P4.4).

This wrapper intentionally does NOT move the ``.gen_*.py`` files: they stay
runnable standalone for archaeology, while ``gen.py`` is the safe, documented
entrypoint that captures their writes. Stdlib-only (no Frappe dependency).
"""
import argparse
import builtins
import difflib
import importlib.util
import io
import os
import sys

REPO = os.path.dirname(os.path.abspath(__file__))
BACKEND_ROOT = os.path.expanduser("~/frappe-bench/apps/gam")

# target -> (generator file, stale?, destructive?)
# NOTE: every target is STALE as of this writing — verified by `gen.py all`.
# `destructive=True` marks targets whose template is a known truncation hazard.
TARGETS = {
    "backend":   (".gen_backend.py",  True,  False),
    "doctypes":  (".gen_doctypes.py", True,  False),
    "tests":     (".gen_tests.py",    True,  False),
    "api":       (".gen_api.py",      True,  True),
}

BANNER = (
    "# DO NOT EDIT — generated by gen.py (target: {target}).\n"
    "# To change, edit the corresponding .gen_{target}.py template, then run\n"
    "# `python gen.py {target} --write --banner`. Hand-edits are overwritten.\n\n"
)

# Files that must NOT receive the banner (patched in place, or package inits
# that are conventionally empty — bannering them is pure noise).
NO_BANNER_FILES = {"hooks.py", "__init__.py"}

# Non-destructive targets included in `all` (api is excluded — destructive).
ALL_TARGETS = ("backend", "doctypes", "tests")


def _load_module(target, genfile):
    """Load a dotfile generator (e.g. .gen_backend.py) as an importable module."""
    path = os.path.join(REPO, genfile)
    spec = importlib.util.spec_from_file_location("_gen_" + target, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


class _CaptureBuffer(io.StringIO):
    """A text-mode write target that records (abspath, content) on close.

    Returned by the monkeypatched ``open`` for write modes, so a generator's
    ``with open(path, 'w') as fh: fh.write(...)`` captures instead of writing.
    """

    def __init__(self, path, owner):
        super().__init__()
        self._path = path
        self._owner = owner
        self._recorded = False

    def close(self):
        if not self._recorded:
            self._recorded = True
            self._owner.writes.append((self._path, self.getvalue()))
        super().close()


class _NullBuffer:
    """Sink for unexpected binary writes (no generator currently uses them)."""

    def write(self, *_a, **_k):
        return 0

    def close(self):
        pass


class _Capture:
    """Monkeypatch harness: captures write-mode ``open`` + neutralises
    ``os.makedirs`` while a generator runs, so dry-run leaves the FS untouched."""

    def __init__(self):
        self.real_open = builtins.open
        self.real_makedirs = os.makedirs
        self.writes = []  # list[(abspath, content_str)]

    def open(self, file, mode="r", *a, **k):
        is_write = any(m in mode for m in ("w", "x"))
        if is_write:
            if "b" in mode:
                return _NullBuffer()
            return _CaptureBuffer(os.path.abspath(file), self)
        return self.real_open(file, mode, *a, **k)

    def makedirs(self, _name, *_a, **_k):
        # No-op so dry-run doesn't seed the backend tree with empty dirs.
        return

    def __enter__(self):
        builtins.open = self.open
        os.makedirs = self.makedirs
        return self

    def __exit__(self, *_exc):
        builtins.open = self.real_open
        os.makedirs = self.real_makedirs
        return False


def _capture(target, genfile):
    """Run a generator with writes captured; return list[(abspath, content)]."""
    cap = _Capture()
    saved_stdout = sys.stdout
    sys.stdout = io.StringIO()  # swallow the generator's own "wrote ..." prints
    try:
        mod = _load_module(target, genfile)
        with cap:
            if not hasattr(mod, "main"):
                raise SystemExit(f"{genfile} has no main()")
            mod.main()
    finally:
        sys.stdout = saved_stdout
    return cap.writes


def _with_banner(target, abspath, content):
    """Prepend the DO-NOT-EDIT banner to wholesale-generated .py files only.

    Skipped for: non-.py (JSON breaks on ``#``), empty content, package inits,
    and hooks.py (patched in place rather than generated wholesale). Only used
    when ``--banner`` is explicitly passed (default off — see module docstring).
    """
    if not abspath.endswith(".py"):
        return content
    if os.path.basename(abspath) in NO_BANNER_FILES:
        return content
    if not content.strip():
        return content
    if content.startswith("# DO NOT EDIT"):
        return content
    return BANNER.format(target=target) + content


def _existing(path):
    try:
        with open(path, encoding="utf-8") as fh:
            return fh.read()
    except FileNotFoundError:
        return None


def _run(target, write, force, banner):
    genfile, stale, destructive = TARGETS[target]

    # --write on a STALE target is refused without --force. Dry-run is always
    # allowed (read-only diagnostic) so drift stays visible.
    if stale and write and not force:
        tag = "STALE/DESTRUCTIVE" if destructive else "STALE"
        print(f"✗ refusing to --write {tag} target '{target}'.", file=sys.stderr)
        print("  The live file is the source of truth; regenerating would clobber "
              "hand-edits.", file=sys.stderr)
        print("  Re-run with --force ONLY after regenerating the template from the "
              "live file (plans P4.4).", file=sys.stderr)
        return 2

    if not os.path.isdir(BACKEND_ROOT):
        print(f"○ backend not present ({BACKEND_ROOT}) — nothing to verify for '{target}'.")
        return 0

    if stale:
        tag = "STALE/DESTRUCTIVE" if destructive else "STALE"
        print(f"⚠️  target '{target}' is {tag} (live backend is the source of truth).")
    if destructive and write:
        print("⚠️  APPLYING A DESTRUCTIVE STALE GENERATOR — this truncates live code!",
              file=sys.stderr)

    writes = _capture(target, genfile)
    changed = 0
    for abspath, content in writes:
        if banner:
            content = _with_banner(target, abspath, content)
        existing = _existing(abspath)
        rel = os.path.relpath(abspath, BACKEND_ROOT)
        if existing == content:
            print(f"  ✓ {rel} (in sync)")
            continue
        changed += 1
        if write:
            os.makedirs(os.path.dirname(abspath), exist_ok=True)
            with open(abspath, "w", encoding="utf-8") as fh:
                fh.write(content)
            print(f"  ✎ wrote {rel}")
        else:
            print(f"  ✗ {rel} — DRIFT")
            diff = difflib.unified_diff(
                (existing or "").splitlines(keepends=True),
                content.splitlines(keepends=True),
                fromfile=f"{rel} (live)",
                tofile=f"{rel} (gen)",
                n=2,
            )
            sys.stdout.writelines(diff)

    if write:
        print(f"\napplied {changed} file(s) for target '{target}'.")
        return 0
    if changed:
        print(f"\n{changed} file(s) would change (dry-run). --write is refused for "
              f"STALE targets without --force.")
        return 1
    print(f"\n✓ target '{target}' is in sync (0 drift).")
    return 0


def _status():
    print("GAM generators — target health\n")
    for name, (genfile, stale, destructive) in TARGETS.items():
        if destructive:
            tag = "STALE/DESTRUCTIVE"
        elif stale:
            tag = "STALE"
        else:
            tag = "AUTHORITATIVE"
        presence = "✓ backend present" if os.path.isdir(BACKEND_ROOT) else "○ backend absent"
        print(f"  {name:<10} {tag:<20} {genfile:<20} {presence}")
    print("\nEvery target is STALE: the live backend is the source of truth.")
    print("`all` is a read-only drift report (dry-run). --write needs --force.")


def main(argv=None):
    p = argparse.ArgumentParser(
        prog="gen.py",
        description="Single, safe entrypoint for GAM code generation.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Default mode is dry-run (read-only). See module docstring for the safety model.",
    )
    p.add_argument("target", nargs="?", choices=list(TARGETS) + ["all", "status"],
                   help="generator target, 'all' (drift report), or 'status'")
    p.add_argument("--write", action="store_true",
                   help="apply changes (default: dry-run). Refused for STALE targets without --force.")
    p.add_argument("--force", action="store_true",
                   help="allow --write on STALE targets (only after regenerating the template)")
    p.add_argument("--banner", action="store_true",
                   help="prepend a `# DO NOT EDIT` banner to .py outputs (opt-in)")
    args = p.parse_args(argv)

    if not args.target:
        p.print_help()
        return 0
    if args.target == "status":
        _status()
        return 0
    if args.target == "all":
        rc = 0
        for t in ALL_TARGETS:  # non-destructive targets only (api excluded)
            print(f"\n=== {t} ===")
            rc |= _run(t, args.write, args.force, args.banner)
        return rc
    return _run(args.target, args.write, args.force, args.banner)


if __name__ == "__main__":
    sys.exit(main())
